name: Publish package

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install
    
    - uses: primer/publish@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
